language: c
sudo: false
os:
  - linux
  - osx
#  - windows
compiler:
  - clang
  - gcc
script: make test
matrix:
  include:
    - os: linux
      compiler: msvc98
      script: make vc98
      sudo: required
      services:
        - docker
    - os: linux
      compiler: arduino
      sudo: required
      before_install:
        - wget http://downloads.arduino.cc/arduino-cli/arduino-cli-latest-linux64.tar.bz2
        - tar xf arduino-cli-latest-linux64.tar.bz2
        - mkdir -p $HOME/bin
        - mv arduino-cli-*-linux64 $HOME/bin/arduino-cli
        - export PATH=$PATH:$HOME/bin
        - arduino-cli core update-index
        - arduino-cli core install arduino:avr;
      script:
        - arduino-cli sketch new TestSketch
        - cp $PWD/example/shadow.ino mjson.h $HOME/Arduino/TestSketch
        - arduino-cli compile --verbose --warnings all --fqbn arduino:avr:nano $HOME/Arduino/TestSketch
