language: c
sudo: false
# after_success: bash <(curl -s https://codecov.io/bash)
os:
  - linux
  - osx
#  - windows
compiler:
  - clang
  - gcc
script: make -C test
matrix:
  include:
    - os: linux
      compiler: msvc98
      script: make -C test vc98
      sudo: required
      services:
        - docker
    - os: linux
      compiler: arduino
      sudo: required
      before_install:
        - wget http://downloads.arduino.cc/arduino-1.8.9-linux64.tar.xz
        - tar xf arduino-1.8.9-linux64.tar.xz
        - sudo mv arduino-1.8.9 /usr/local/share/arduino
        - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
      script:
        - cp -r examples/ArduinoDeviceShadowExample /tmp
        - cp src/mjson.h /tmp/ArduinoDeviceShadowExample
        - arduino --verify --board arduino:avr:uno /tmp/ArduinoDeviceShadowExample/ArduinoDeviceShadowExample.ino

