name: build
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: make -C test
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -C test
  windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: vc98
      run: make -C test vc98
    - name: vc2017
      run: make -C test vc2017
  arm:
    runs-on: ubuntu-latest
    steps:
    - name: arm
      run: make -C test arm
